DROP DATABASE mydb;
-- MySQL Script generated by MySQL Workbench
-- Sun May 28 11:33:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(256) NULL,
  `senha` CHAR(60) NULL,
  `cpf` CHAR(11) NULL,
  `telefone` CHAR(11) NULL,
  `orcamento_min` DECIMAL(8,2) NULL,
  `orcamento_max` DECIMAL(8,2) NULL,
  `descricao` VARCHAR(270) NULL,
  `presta_aula` TINYINT(1) NULL,
  `plano` INT NULL,
  `status` INT NULL,
  `anexo_pfp` VARCHAR(150) NULL,
  `acessos` INT NULL,
  `tipo_usuario` INT NULL,
  `canal` INT NULL,
  `area_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_area1_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dados_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dados_endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(25) NULL,
  `cidade` VARCHAR(35) NULL,
  `cep` CHAR(8) NULL,
  `bairro` VARCHAR(35) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(25) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dados_endereco_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_dados_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area_id` INT NOT NULL,
  `nome` VARCHAR(90) NULL,
  PRIMARY KEY (`id`, `area_id`),
  INDEX `fk_tipo_servico_area1_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_servico_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contratante_usuario_id` INT NOT NULL,
  `prestador_usuario_id` INT NOT NULL,
  `nota` INT NULL,
  `descricao` VARCHAR(75) NULL,
  PRIMARY KEY (`id`, `contratante_usuario_id`, `prestador_usuario_id`),
  INDEX `fk_avaliacao_usuario1_idx` (`contratante_usuario_id` ASC) VISIBLE,
  INDEX `fk_avaliacao_usuario2_idx` (`prestador_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`contratante_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario2`
    FOREIGN KEY (`prestador_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contratante_usuario_id` INT NOT NULL,
  `prestador_usuario_id` INT NOT NULL,
  `tamanho` DECIMAL(10,3) NULL,
  `medida` VARCHAR(10) NULL,
  `descricao` VARCHAR(120) NULL,
  `status` INT NULL,
  `servico_id` INT NOT NULL,
  `avaliacao_id` INT NULL,
  PRIMARY KEY (`id`, `contratante_usuario_id`, `prestador_usuario_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_solicitacao_usuario1_idx` (`contratante_usuario_id` ASC) VISIBLE,
  INDEX `fk_solicitacao_usuario2_idx` (`prestador_usuario_id` ASC) VISIBLE,
  INDEX `fk_solicitacao_tipo_servico1_idx` (`servico_id` ASC) VISIBLE,
  INDEX `fk_solicitacao_avaliacao1_idx` (`avaliacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacao_usuario1`
    FOREIGN KEY (`contratante_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_usuario2`
    FOREIGN KEY (`prestador_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_tipo_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_avaliacao1`
    FOREIGN KEY (`avaliacao_id`)
    REFERENCES `mydb`.`avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitacao_id` INT NOT NULL,
  `id_remetente` INT NOT NULL,
  `mensagem` VARCHAR(150) NULL,
  `horario` DATETIME NULL,
  `anexo` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `solicitacao_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_chat_solicitacao1_idx` (`solicitacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_solicitacao1`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `mydb`.`solicitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prospect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prospect` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `opt_canal` INT NULL,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(256) NULL,
  `fone` CHAR(13) NULL,
  `opt_cidade` INT NULL,
  `bln_conhece_manuall` TINYINT(1) NULL,
  `bln_aprender` TINYINT(1) NULL,
  `bln_interesse_manuall` TINYINT(1) NULL,
  `bln_interesse_ensinar` TINYINT(1) NULL,
  `bln_conhece_semelhante` TINYINT(1) NULL,
  `bln_cupom` TINYINT(1) NULL,
  `msg_desistencia` VARCHAR(90) NULL,
  `status` INT NULL,
  `tipo_usuario` INT NULL,
  `area_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prospect_area1_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `fk_prospect_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`token_blacklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`token_blacklist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `servico_id`),
  INDEX `fk_usuario_has_servico_servico1_idx` (`servico_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_servico_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_servico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitacao_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitacao_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitacao_id` INT NOT NULL,
  `anexo` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `solicitacao_id`),
  INDEX `fk_solicitacao_img_solicitacao1_idx` (`solicitacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacao_img_solicitacao1`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `mydb`.`solicitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitacao_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitacao_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitacao_id` INT NOT NULL,
  `anexo` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `solicitacao_id`),
  INDEX `fk_solicitacao_img_solicitacao1_idx` (`solicitacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacao_img_solicitacao1`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `mydb`.`solicitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `anexo` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_usuario_img_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_img_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`form_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`form_orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contratante_usuario_id` INT NOT NULL,
  `prestador_usuario_id` INT NOT NULL,
  `mensagem` VARCHAR(135) NULL,
  `orcamento` DECIMAL(9,2) NULL,
  PRIMARY KEY (`id`, `contratante_usuario_id`, `prestador_usuario_id`),
  INDEX `fk_form_orcamento_usuario1_idx` (`prestador_usuario_id` ASC) VISIBLE,
  INDEX `fk_form_orcamento_usuario2_idx` (`contratante_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_form_orcamento_usuario1`
    FOREIGN KEY (`prestador_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_orcamento_usuario2`
    FOREIGN KEY (`contratante_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`desc_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`desc_servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `topico` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_desc_servicos_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_desc_servicos_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO area (nome) VALUES
("Jardineiro"),
("Pintor"),
("Eletricista"),
("Encanador"),
("Marceneiro"),
("Montador"),
("Gesseiro");

INSERT INTO servico (area_id, nome) VALUES
(1, "Poda"),
(1, "Controle de Pragas"),
(1, "Adubagem"),
(3, "Conserto de resistência de chuveiro"),
(3, "Troca de fiação"),
(3, "Troca de lâmpada");

INSERT INTO usuario
(`nome`, `email`, `senha`, `cpf`, `telefone`, `orcamento_min`, `orcamento_max`, `descricao`, `presta_aula`, `plano`, `status`, `anexo_pfp`, `acessos`, `tipo_usuario`, `canal`, `area_id`)
VALUES
('Joaquim Gimenes Pires', 'joaquim.pires@sptech.school', '$2a$10$Pfz3ATcOC0jdOt4F36IxGuGBrfRtxovR1LAZkWoolJRdd7xVF.4sS', '12345678901', '11987654321', 500.00, 1000.00, 'Sou um professor experiente', 1, 1, 2, 'https://static-cse.canva.com/blob/759723/DrobotDeanCanva.jpg', 0, 1, 0, 1),
('Maria Santos', 'maria.santos@example.com', '$2a$10$cBT.xH1jVvoCDdc/SEwaOutmAUlZoTVBsDxawF42yAW136grzNMpa', '98765432109', '11976543210', 1000.00, 2000.00, 'Ofereço aulas particulares', 0, 2, 2, 'https://imagens.usp.br/wp-content/uploads/Campus-15-Foto-Marcos-Santos20101220_066.jpg', 0, 2, 1, 3),
('Ana Oliveira', 'ana.oliveira@example.com', '$2a$10$5ph0RY7U8DKcKkHKJgYjPOToAtW6y0ZfQygJSiR4j2DYeFSKytJni', '76543210987', '11965432109', 1500.00, 3000.00, 'Posso ajudar em diversas disciplinas', 1, 3, 2, 'https://i.pinimg.com/originals/f5/67/bf/f567bfd530f04a3aff832f38844fe5be.jpg', 0, 1, 4, 5),
('Fernanda Souza', 'fernanda.souza@example.com', '$2a$10$IMisr8TdWydcgH22StC/lutUcdtDmqYVDWxyJmZmQX8Tp.nraC5dq', '23456789012', '11912345678', 800.00, 1500.00, 'Professora de Matemática', 1, 3, 2, 'perfil.jpg', 0, 1, 3, 2),
('Rafaela Lima', 'rafaela.lima@example.com', '$2a$10$NFvy/hCRZkaEMiE468y1quooIfRTVWPJEAAE2772.iry.TCCaYO3a', '34567890123', '11923456789', 1200.00, 2000.00, 'Especialista em Ciências', 0, 2, 2, 'foto.png', 0, 2, 1, 6),
('Carlos Mendes', 'carlos.mendes@example.com', '$2a$10$UT.ocrWrVawMkbqVc/6RN.NALwJOcuKIXupneVOZ.nlnWX3KBEKQy', '45678901234', '11934567890', 1500.00, 3000.00, 'Aulas de Inglês para todos os níveis', 1, 1, 2, 'avatar.jpg', 0, 1, 4, 7),
('Pedro Santos', 'pedro.santos@example.com', '$2a$10$DdOzkLpv3MWFxIijfxBNGONl3kHALH//z4G27bTGd92mq9dZRdJiS', '56789012345', '11945678901', 800.00, 1500.00, 'Professor de História', 1, 2, 2, 'perfil.jpg', 0, 1, 1, 3),
('Mariana Oliveira', 'mariana.oliveira@example.com', '$2a$10$GLZUkiDGCqZG9LX7YC/tRuPVBCNtaEhDlf.KvYtiSI7TkQ41.0zNu', '67890123456', '11956789012', 1200.00, 2000.00, 'Especialista em Biologia', 0, 1, 2, 'foto.png', 0, 2, 1, 5),
('Pedro Oliveira', 'pedro.oliveira@example.com', '$2a$10$u8ZWxnPbnTQfU1lWRNBq1Ouc1TFdBoz6GGJfhmMd1ULWliTirNH4O', '34567890123', '11965432107', 2000.00, 3000.00, 'Descrição do usuário 3', 1, 3, 2, 'anexo3.jpg', 0, 2, 2, 3),
('Ana Souza', 'ana.souza@example.com', '$2a$10$AOnNkhW49gT6wW6t46Hbuenh7MEJqRAtTiIocj7chIGIq6rn2g87S', '45678901234', '11954321098', 2500.00, 3500.00, 'Descrição do usuário 4', 0, 1, 2, 'anexo4.jpg', 0, 2, 3, 4),
('Lucas Ferreira', 'lucas.ferreira@example.com', '$2a$10$Nx2rDH7u93q2bM3XFA4bTeUusk3AKN18yqE2hddIhNRXPAEFHd2zm', '56789012345', '11943210987', 3000.00, 4000.00, 'Descrição do usuário 5', 1, 2, 2, 'anexo5.jpg', 0, 1, 4, 5),
('Fernanda Rodrigues', 'fernanda.rodrigues@example.com', '$2a$10$cNXBWXutEmZLpCFZV/X8duyms0Nfkq6E4/yhrSdsGCjkK90qS8zC.', '67890123456', '11932109876', 3500.00, 4500.00, 'Descrição do usuário 6', 1, 3, 2, 'anexo6.jpg', 0, 1, 3, 6),
('Gustavo Lima', 'gustavo.lima@example.com', '$2a$10$of6uGGU9YmW4t29qTsgnaedhdGvT7J03JoC5E5mAwdnqdHuVIb7tG', '78901234567', '11921098765', 4000.00, 5000.00, 'Descrição do usuário 7', 0, 1, 2, 'anexo7.jpg', 0, 2, 4, 7),
('Juliana Almeida', 'juliana.almeida@example.com', '$2a$10$cischjBywyKBTR5QEVuOBOtnEF5AMesyj0YIOlxsLghwalKHzwvWa', '89012345678', '11910987654', 4500.00, 5500.00, 'Descrição do usuário 8', 1, 2, 2, 'anexo8.jpg', 0, 1, 0, 1),
('Rafael Martins', 'rafael.martins@example.com', '$2a$10$Cx06v8rau8pXFYOGTe28leArpQq1gzmsxc.2elyxthfEVaNQl6HUK', '90123456789', '11909876543', 5000.00, 6000.00, 'Descrição do usuário 9', 0, 3, 2, 'anexo9.jpg', 0, 2, 1, 2),
('Camila Gomes', 'camila.gomes@example.com', '$2a$10$5nP0d/R1NRI02FygaUviFOBojVFljzJyScPlGhOVxjG3fTPQ9IAC.', '01234567890', '11998765432', 5500.00, 6500.00, 'Descrição do usuário 10', 1, 2, 2, 'anexo10.jpg', 0, 1, 2, 3),
('Ricardo Santos', 'ricardo.santos@example.com', '$2a$10$W3EcOn.A/DFF/eCyQXgHSOBnzFMYsuVL8QFx.NMSnbqswH/SthAHe', '12345678901', '11987654321', 1000.00, 2000.00, 'Descrição do usuário 11', 1, 1, 2, 'anexo11.jpg', 0, 1, 0, 1),
('Amanda Oliveira', 'amanda.oliveira@example.com', '$2a$10$DiZnbfv.2Zz/YkwAmfnvtOnF8TMTIKiD29gyEAhySsHPGN7UAGwIW', '23456789012', '11976543210', 1500.00, 2500.00, 'Descrição do usuário 12', 0, 2, 2, 'anexo12.jpg', 0, 1, 1, 2),
('Gabriel Rodrigues', 'gabriel.rodrigues@example.com', '$2a$10$UdS5.K.yHjQjbeBv0RsVvel3bo.KFdaV0KOZWPa/R60T8ZjLqXkDm', '34567890123', '11965432107', 2000.00, 3000.00, 'Descrição do usuário 13', 1, 3, 2, 'anexo13.jpg', 0, 2, 2, 3),
('Carolina Souza', 'carolina.souza@example.com', '$2a$10$aXk4jmNvpTMhWpksBpqqrusqeX7ENeBvgWpnBSl3ZFzypzcB3ApoG', '45678901234', '11954321098', 2500.00, 3500.00, 'Descrição do usuário 14', 0, 1, 2, 'anexo14.jpg', 0, 2, 3, 4),
('Matheus Ferreira', 'matheus.ferreira@example.com', '$2a$10$KRIagtT591nRBgkGCXJoFOiTIaztE/GhqlNkTyVETiYvWfn3VeqDm', '56789012345', '11943210987', 3000.00, 4000.00, 'Descrição do usuário 15', 1, 2, 2, 'anexo15.jpg', 0, 1, 4, 5);


INSERT INTO dados_endereco VALUES (null, "São Paulo", "São Paulo", "03077000", "Tatuapé", "Rua Ulisses Cruz", "668", null, 1);

INSERT INTO avaliacao VALUES (null, 1, 2, 4, "Muito bom o serviço, mas demorou mais que o esperado"),
							 (null, 2, 1, 5, "Sensacional! Serviço impecável");

INSERT INTO solicitacao VALUES (null, 1, 2, 50.000, "m2", "Quebar meu banheiro inteiro", 2, 1, 1),
							   (null, 2, 1, 25.00, "m2", "Quebrar minha cozinha inteira", 2, 2, 2);

INSERT INTO chat
(solicitacao_id, id_remetente, mensagem, horario)
values
(1, 1, "opa", '2023-05-21 14:30:00'),
(1, 2, "eai, td bem??", '2023-05-21 14:30:00');

INSERT INTO usuario_img VALUES (null, 1, "https://source.unsplash.com/800x600/daily"),
							   (null, 1, "https://loremflickr.com/400/300"),
                               (null, 1, "https://placeimg.com/800/600/nature");

INSERT INTO usuario_servico VALUES (null, 1, 1),
								   (null, 1, 2),
                                   (null, 1, 3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
